# Generated by Django 3.2.18 on 2023-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KubeConfigInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名称')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=16, verbose_name='角色')),
                ('service_name', models.CharField(max_length=128, null=True, verbose_name='服务名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('review_time', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('modify_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('expired_time', models.IntegerField(null=True, verbose_name='过期间隔时间,单位:day')),
                ('send_ok', models.BooleanField(null=True, verbose_name='邮件发送ok')),
            ],
            options={
                'verbose_name': 'kubeconfig_info生成信息表',
                'db_table': 'kubeconfig_info',
            },
        ),
    ]
