# Generated by Django 3.2.18 on 2023-03-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kubeconfiginfo',
            options={'verbose_name': 'kubeconfig_info生成信息表', 'verbose_name_plural': 'kubeconfig_info生成信息表'},
        ),
    ]
