# Generated by Django 3.2.14 on 2022-07-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220721_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active',
        ),
    ]
