# Generated by Django 3.2.14 on 2023-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwcloudscaneipportinfo',
            name='service_info',
            field=models.CharField(max_length=2048, null=True, verbose_name='服务器版本信息'),
        ),
    ]
