pwd:
mysql_host:
mysql_port:
mysql_user:
mysql_password:
obs_ak:
obs_sk:
obs_url:
obs_domain_id:
uptime_robot_api_key:
alarm_email_host:
alarm_email_user:
alarm_email_pwd:
ALARM_SMS_URL:
ALARM_SMS_KEY:
ALARM_SMS_SECRET:
ALARM_SMS_SENDER:
ALARM_SMS_ALARM_TEMPLATE:
ALARM_SMS_RECOVER_TEMPLATE:
GITHUB_SECRET: