# Generated by Django 3.2.18 on 2023-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuResourceUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='服务器名称')),
                ('create_time', models.IntegerField(null=True, verbose_name='创建时间戳')),
                ('lower_cpu_count', models.IntegerField(null=True, verbose_name='低cpu统计:<10%的cpu统计个数, 不包含10%')),
                ('medium_lower_cpu_count', models.IntegerField(null=True, verbose_name='中低cpu统计:10-50%的cpu统计个数, 不包含50%')),
                ('medium_high_cpu_count', models.IntegerField(null=True, verbose_name='中高cpu统计:50-90%的cpu统计个数, 不包含90%')),
                ('high_cpu_count', models.IntegerField(null=True, verbose_name='高cpu统计:>90%的cpu统计个数')),
            ],
            options={
                'verbose_name': '服务器cpu资源利用率统计',
                'db_table': 'cpu_resource_utilization',
            },
        ),
        migrations.CreateModel(
            name='HWCloudBillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_cycle', models.CharField(max_length=16, verbose_name='账期(单位月)')),
                ('account', models.CharField(max_length=32, verbose_name='华为云账户名称')),
                ('resource_type_name', models.CharField(max_length=64, verbose_name='云服务类型名称')),
                ('consume_amount', models.FloatField(verbose_name='应付金额')),
                ('discount_rate', models.FloatField(null=True, verbose_name='折扣率')),
                ('actual_cost', models.FloatField(null=True, verbose_name='实际费用')),
            ],
            options={
                'verbose_name': '华为云账单信息',
                'db_table': 'hw_cloud_bill_info',
            },
        ),
        migrations.CreateModel(
            name='MemResourceUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='服务器名称')),
                ('create_time', models.IntegerField(null=True, verbose_name='创建时间戳')),
                ('lower_mem_count', models.IntegerField(null=True, verbose_name='低mem统计:<10%的cpu统计个数, 不包含10%')),
                ('medium_lower_mem_count', models.IntegerField(null=True, verbose_name='中低mem统计:10-50%的cpu统计个数, 不包含50%')),
                ('medium_high_mem_count', models.IntegerField(null=True, verbose_name='中高mem统计:50-90%的cpu统计个数, 不包含90%')),
                ('high_mem_count', models.IntegerField(null=True, verbose_name='高mem统计:>90%的mem统计个数')),
            ],
            options={
                'verbose_name': '服务器内存资源利用率统计',
                'db_table': 'mem_resource_utilization',
            },
        ),
    ]
