# Generated by Django 3.2.18 on 2023-03-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpuresourceutilization',
            options={'verbose_name': '服务器cpu资源利用率统计', 'verbose_name_plural': '服务器cpu资源利用率统计'},
        ),
        migrations.AlterModelOptions(
            name='hwcloudbillinfo',
            options={'verbose_name': '华为云账单信息', 'verbose_name_plural': '华为云账单信息'},
        ),
        migrations.AlterModelOptions(
            name='memresourceutilization',
            options={'verbose_name': '服务器内存资源利用率统计', 'verbose_name_plural': '服务器内存资源利用率统计'},
        ),
    ]
