# Generated by Django 3.2.18 on 2023-04-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='community',
            field=models.CharField(max_length=64, null=True, verbose_name='社区'),
        ),
        migrations.AlterField(
            model_name='servicesla',
            name='url',
            field=models.CharField(max_length=128, null=True, verbose_name='服务域名'),
        ),
    ]
