# Generated by Django 3.2.18 on 2023-06-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0003_alter_servicesla_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIntroduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='服务名称')),
                ('service_introduce', models.CharField(blank=True, max_length=128, null=True, verbose_name='服务介绍')),
                ('service_lang', models.CharField(choices=[('en', 'en'), ('zh', 'zh')], max_length=4, verbose_name='语言')),
                ('service_sla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_resources.servicesla')),
            ],
            options={
                'verbose_name': '服务介绍表',
                'verbose_name_plural': '服务介绍表',
                'db_table': 'service_introduce',
            },
        ),
    ]
