# Generated by Django 3.2.18 on 2023-03-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouds_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hwcloudhighriskport',
            options={'verbose_name': '华为云高危端口', 'verbose_name_plural': '华为云高危端口'},
        ),
        migrations.AlterModelOptions(
            name='hwcloudscaneipportinfo',
            options={'verbose_name': '华为云高危端口扫描信息', 'verbose_name_plural': '华为云高危端口扫描信息'},
        ),
        migrations.AlterModelOptions(
            name='hwcloudscaneipportstatus',
            options={'verbose_name': '华为云高危端口扫描状态表', 'verbose_name_plural': '华为云高危端口扫描状态表'},
        ),
        migrations.AlterModelOptions(
            name='hwcloudscanobsanonymousbucket',
            options={'verbose_name': '华为云对象系统匿名桶', 'verbose_name_plural': '华为云对象系统匿名桶'},
        ),
        migrations.AlterModelOptions(
            name='hwcloudscanobsanonymousfile',
            options={'verbose_name': '华为云对象系统匿名文件', 'verbose_name_plural': '华为云对象系统匿名文件'},
        ),
        migrations.AlterModelOptions(
            name='hwcloudscanobsanonymousstatus',
            options={'verbose_name': '华为云对象系统匿名桶状态表', 'verbose_name_plural': '华为云对象系统匿名桶状态表'},
        ),
    ]
