# Generated by Django 3.2.18 on 2023-04-27 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.IntegerField(verbose_name='报警code')),
                ('alarm_level', models.IntegerField(verbose_name='报警级别')),
                ('alarm_module', models.IntegerField(verbose_name='报警模块')),
                ('alarm_name', models.CharField(max_length=64, verbose_name='报警名字')),
                ('alarm_details', models.TextField(verbose_name='报警详细信息')),
                ('alarm_md5', models.CharField(db_index=True, max_length=64, verbose_name='报警信息的md5')),
                ('is_recover', models.BooleanField(default=False, verbose_name='报警是否恢复, False没有恢复/True恢复')),
                ('alarm_happen_time', models.DateTimeField(verbose_name='报警第一次发生时间')),
                ('alarm_recover_time', models.DateTimeField(null=True, verbose_name='报警恢复时间')),
                ('alarm_refresh_time', models.DateTimeField(null=True, verbose_name='报警刷新时间')),
            ],
            options={
                'verbose_name': '报警表',
                'db_table': 'alarm',
            },
        ),
        migrations.CreateModel(
            name='AlarmNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='报警手机号')),
                ('desc', models.CharField(max_length=255, verbose_name='报警Email信息')),
            ],
            options={
                'verbose_name': '报警通知',
                'db_table': 'alarm_notify',
            },
        ),
        migrations.CreateModel(
            name='AlarmNotifyStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_name', models.IntegerField(verbose_name='报警名字id')),
                ('alarm_keywords', models.CharField(max_length=255, verbose_name='报警详细信息关键字')),
                ('alarm_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.alarmnotify', verbose_name='报警通知')),
            ],
            options={
                'verbose_name': '报警通知策略',
                'db_table': 'alarm_notify_strategy',
            },
        ),
    ]
