# Generated by Django 3.2.18 on 2023-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotify',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='报警手机号'),
        ),
    ]
