# Generated by Django 3.2.18 on 2023-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HWColudObsInteract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='华为云IAM用户')),
                ('community', models.CharField(max_length=16, verbose_name='社区')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户id')),
                ('password', models.CharField(max_length=64, verbose_name='用户密码')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除')),
            ],
            options={
                'verbose_name': '华为云对象上传系统',
                'db_table': 'hw_cloud_obs_interact',
            },
        ),
    ]
