# Generated by Django 3.2.18 on 2023-03-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hwcoludobsinteract',
            options={'verbose_name': '华为云对象上传系统', 'verbose_name_plural': '华为云对象上传系统'},
        ),
    ]
